const INPUT_PREVIOUS_VALUE_DATA_ATTRIBUTE = "data-previous-value"
const INPUT_PREVIOUS_POSITION_DATA_ATTRIBUTE = "data-previous-position"

export {
    INPUT_PREVIOUS_POSITION_DATA_ATTRIBUTE,
    INPUT_PREVIOUS_VALUE_DATA_ATTRIBUTE,
}
