import {RecordKey} from "@sagittal/general"
import {NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP, NOT_SMuFL_ZERO_POSITION_MAP} from "../notSmufl"
import {SMuFL_MAP} from "../smufl"
import {Codeword, Symbol} from "../types"

const CLEF_ALIASES_MAP: Record<RecordKey<Codeword>, Symbol> = {
    "8va": SMuFL_MAP["otal"],
    "8vb": SMuFL_MAP["otbsvb"],
} as Record<Codeword, Symbol>

const GENERIC_POSITION_ALIASES_MAP: Record<RecordKey<Codeword>, Symbol> = {
    "up15": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpsrs15"],
    "up14": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpsrs14"],
    "up13": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpsrs13"],
    "up12": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpsrs12"],
    "up11": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpsrs11"],
    "up10": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpsrs10"],
    "up9": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpsrs9"],
    "up8": SMuFL_MAP["stpsrs8"],
    "up7": SMuFL_MAP["stpsrs7"],
    "up6": SMuFL_MAP["stpsrs6"],
    "up5": SMuFL_MAP["stpsrs5"],
    "up4": SMuFL_MAP["stpsrs4"],
    "up3": SMuFL_MAP["stpsrs3"],
    "up2": SMuFL_MAP["stpsrs2"],
    "up1": SMuFL_MAP["stpsrs1"],
    "up0": NOT_SMuFL_ZERO_POSITION_MAP["stpsrs0"],
    "dn1": SMuFL_MAP["stpslw1"],
    "dn2": SMuFL_MAP["stpslw2"],
    "dn3": SMuFL_MAP["stpslw3"],
    "dn4": SMuFL_MAP["stpslw4"],
    "dn5": SMuFL_MAP["stpslw5"],
    "dn6": SMuFL_MAP["stpslw6"],
    "dn7": SMuFL_MAP["stpslw7"],
    "dn8": SMuFL_MAP["stpslw8"],
    "dn9": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpslw9"],
    "dn10": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpslw10"],
    "dn11": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpslw11"],
    "dn12": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpslw12"],
    "dn13": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpslw13"],
    "dn14": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpslw14"],
    "dn15": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpslw15"],
} as Record<Codeword, Symbol>

const TREBLE_POSITION_ALIASES_MAP: Record<RecordKey<Codeword>, Symbol> = {
    "c7": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpsrs15"],
    "b6": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpsrs14"],
    "a6": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpsrs13"],
    "g6": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpsrs12"],
    "f6": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpsrs11"],
    "e6": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpsrs10"],
    "d6": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpsrs9"],
    "c6": SMuFL_MAP["stpsrs8"],
    "b5": SMuFL_MAP["stpsrs7"],
    "a5": SMuFL_MAP["stpsrs6"],
    "g5": SMuFL_MAP["stpsrs5"],
    "f5": SMuFL_MAP["stpsrs4"],
    "e5": SMuFL_MAP["stpsrs3"],
    "d5": SMuFL_MAP["stpsrs2"],
    "c5": SMuFL_MAP["stpsrs1"],
    "b4": NOT_SMuFL_ZERO_POSITION_MAP["stpsrs0"],
    "a4": SMuFL_MAP["stpslw1"],
    "g4": SMuFL_MAP["stpslw2"],
    "f4": SMuFL_MAP["stpslw3"],
    "e4": SMuFL_MAP["stpslw4"],
    "d4": SMuFL_MAP["stpslw5"],
    "c4": SMuFL_MAP["stpslw6"],
    "b3": SMuFL_MAP["stpslw7"],
    "a3": SMuFL_MAP["stpslw8"],
    "g3": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpslw9"],
    "f3": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpslw10"],
    "e3": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpslw11"],
    "d3": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpslw12"],
    "c3": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpslw13"],
    "b2": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpslw14"],
    "a2": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpslw15"],
} as Record<Codeword, Symbol>

const BASS_POSITION_ALIASES_MAP: Record<RecordKey<Codeword>, Symbol> = {
    "e5": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpsrs15"],
    "d5": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpsrs14"],
    "c5": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpsrs13"],
    "b4": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpsrs12"],
    "a4": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpsrs11"],
    "g4": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpsrs10"],
    "f4": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpsrs9"],
    "e4": SMuFL_MAP["stpsrs8"],
    "d4": SMuFL_MAP["stpsrs7"],
    "c4": SMuFL_MAP["stpsrs6"],
    "b3": SMuFL_MAP["stpsrs5"],
    "a3": SMuFL_MAP["stpsrs4"],
    "g3": SMuFL_MAP["stpsrs3"],
    "f3": SMuFL_MAP["stpsrs2"],
    "e3": SMuFL_MAP["stpsrs1"],
    "d3": NOT_SMuFL_ZERO_POSITION_MAP["stpsrs0"],
    "c3": SMuFL_MAP["stpslw1"],
    "b2": SMuFL_MAP["stpslw2"],
    "a2": SMuFL_MAP["stpslw3"],
    "g2": SMuFL_MAP["stpslw4"],
    "f2": SMuFL_MAP["stpslw5"],
    "e2": SMuFL_MAP["stpslw6"],
    "d2": SMuFL_MAP["stpslw7"],
    "c2": SMuFL_MAP["stpslw8"],
    "b1": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpslw9"],
    "a1": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpslw10"],
    "g1": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpslw11"],
    "f1": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpslw12"],
    "e1": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpslw13"],
    "d1": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpslw14"],
    "c1": NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP["stpslw15"],
} as Record<Codeword, Symbol>

export {
    CLEF_ALIASES_MAP,
    BASS_POSITION_ALIASES_MAP,
    TREBLE_POSITION_ALIASES_MAP,
    GENERIC_POSITION_ALIASES_MAP,
}
