import {RecordKey, Word} from "@sagittal/general"
import {EMPTY_UNICODE} from "../../../constants"
import {Code, Unicode} from "../../types"

const NOT_SMuFL_PITCH_COMMAND_MAP: Record<RecordKey<Code & Word>, Unicode & Word> = {
    "c7": EMPTY_UNICODE,
    "b6": EMPTY_UNICODE,
    "a6": EMPTY_UNICODE,
    "g6": EMPTY_UNICODE,
    "f6": EMPTY_UNICODE,
    "e6": EMPTY_UNICODE,
    "d6": EMPTY_UNICODE,
    "c6": EMPTY_UNICODE,
    "b5": EMPTY_UNICODE,
    "a5": EMPTY_UNICODE,
    "g5": EMPTY_UNICODE,
    "f5": EMPTY_UNICODE,
    "e5": EMPTY_UNICODE,
    "d5": EMPTY_UNICODE,
    "c5": EMPTY_UNICODE,
    "b4": EMPTY_UNICODE,
    "a4": EMPTY_UNICODE,
    "g4": EMPTY_UNICODE,
    "f4": EMPTY_UNICODE,
    "e4": EMPTY_UNICODE,
    "d4": EMPTY_UNICODE,
    "c4": EMPTY_UNICODE,
    "b3": EMPTY_UNICODE,
    "a3": EMPTY_UNICODE,
    "g3": EMPTY_UNICODE,
    "f3": EMPTY_UNICODE,
    "e3": EMPTY_UNICODE,
    "d3": EMPTY_UNICODE,
    "c3": EMPTY_UNICODE,
    "b2": EMPTY_UNICODE,
    "a2": EMPTY_UNICODE,
    "g2": EMPTY_UNICODE,
    "f2": EMPTY_UNICODE,
    "e2": EMPTY_UNICODE,
    "d2": EMPTY_UNICODE,
    "c2": EMPTY_UNICODE,
    "b1": EMPTY_UNICODE,
    "a1": EMPTY_UNICODE,
    "g1": EMPTY_UNICODE,
    "f1": EMPTY_UNICODE,
    "e1": EMPTY_UNICODE,
    "d1": EMPTY_UNICODE,
    "c1": EMPTY_UNICODE,
} as Record<Code & Word, Unicode & Word>

const NOT_SMuFL_POSITION_COMMAND_MAP: Record<RecordKey<Code & Word>, Unicode & Word> = {
    "up15": EMPTY_UNICODE,
    "up14": EMPTY_UNICODE,
    "up13": EMPTY_UNICODE,
    "up12": EMPTY_UNICODE,
    "up11": EMPTY_UNICODE,
    "up10": EMPTY_UNICODE,
    "up9": EMPTY_UNICODE,
    "up8": EMPTY_UNICODE,
    "up7": EMPTY_UNICODE,
    "up6": EMPTY_UNICODE,
    "up5": EMPTY_UNICODE,
    "up4": EMPTY_UNICODE,
    "up3": EMPTY_UNICODE,
    "up2": EMPTY_UNICODE,
    "up1": EMPTY_UNICODE,
    "up0": EMPTY_UNICODE,
    "dn1": EMPTY_UNICODE,
    "dn2": EMPTY_UNICODE,
    "dn3": EMPTY_UNICODE,
    "dn4": EMPTY_UNICODE,
    "dn5": EMPTY_UNICODE,
    "dn6": EMPTY_UNICODE,
    "dn7": EMPTY_UNICODE,
    "dn8": EMPTY_UNICODE,
    "dn9": EMPTY_UNICODE,
    "dn10": EMPTY_UNICODE,
    "dn11": EMPTY_UNICODE,
    "dn12": EMPTY_UNICODE,
    "dn13": EMPTY_UNICODE,
    "dn14": EMPTY_UNICODE,
    "dn15": EMPTY_UNICODE,
} as Record<Code & Word, Unicode & Word>

export {
    NOT_SMuFL_PITCH_COMMAND_MAP,
    NOT_SMuFL_POSITION_COMMAND_MAP,
}
