export {smarts} from "./globals"
export {computeSmartAdvanceAndSmartStaveUnicodeIntroClauseAndUpdateSmartAdvanceAndSmartStave} from "./advanceAndStave"
export {INITIAL_SMARTS} from "./constants"
export {isCommenting} from "./comments"
export {computeSmartPositionAndSmartClefUnicodeIntroClauseAndUpdateSmarts, getUnicodeGivenClef} from "./positionAndClef"
export {shouldNotBeDisplayed} from "./shouldNotBeDisplayed"
