import {NOT_SMuFL_LINE_BREAKS_MAP, NOT_SMuFL_MANUAL_ADVANCE_MAP} from "./advanceAndStave"
import {
    NOT_SMuFL_DEFINE_CUSTOM_NONSYMBOL_MAP,
    NOT_SMuFL_SMART_ADVANCE_NONSYMBOL_MAP,
    NOT_SMuFL_SMART_SPACING_NONSYMBOL_MAP,
    NOT_SMuFL_SMART_STAVE_NONSYMBOL_MAP,
} from "./nonsymbol"
import {NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP, NOT_SMuFL_ZERO_POSITION_MAP} from "./positionAndClef"

const NOT_SMuFL_CODES = {
    ...NOT_SMuFL_LINE_BREAKS_MAP,
    ...NOT_SMuFL_SMART_STAVE_NONSYMBOL_MAP,
    ...NOT_SMuFL_SMART_SPACING_NONSYMBOL_MAP,
    ...NOT_SMuFL_MANUAL_ADVANCE_MAP,
    ...NOT_SMuFL_SMART_ADVANCE_NONSYMBOL_MAP,
    ...NOT_SMuFL_DEFINE_CUSTOM_NONSYMBOL_MAP,
    ...NOT_SMuFL_SUPPLEMENTAL_POSITION_MAP,
    ...NOT_SMuFL_ZERO_POSITION_MAP,
}

export {
    NOT_SMuFL_CODES,
}
