import {RecordKey, Word} from "@sagittal/general"
import {NOT_SMuFL_CODES} from "../../notSmufl"
import {SMuFL_MAP} from "../../smufl"
import {Code, Unicode} from "../../types"

const TREBLE_CONDITIONAL_POSITION_ALIASES_MAP: Record<RecordKey<Code & Word>, Unicode & Word> = {
    "C7": NOT_SMuFL_CODES["staffPosRaise15"],
    "B6": NOT_SMuFL_CODES["staffPosRaise14"],
    "A6": NOT_SMuFL_CODES["staffPosRaise13"],
    "G6": NOT_SMuFL_CODES["staffPosRaise12"],
    "F6": NOT_SMuFL_CODES["staffPosRaise11"],
    "E6": NOT_SMuFL_CODES["staffPosRaise10"],
    "D6": NOT_SMuFL_CODES["staffPosRaise9"],
    "C6": SMuFL_MAP["staffPosRaise8"],
    "B5": SMuFL_MAP["staffPosRaise7"],
    "A5": SMuFL_MAP["staffPosRaise6"],
    "G5": SMuFL_MAP["staffPosRaise5"],
    "F5": SMuFL_MAP["staffPosRaise4"],
    "E5": SMuFL_MAP["staffPosRaise3"],
    "D5": SMuFL_MAP["staffPosRaise2"],
    "C5": SMuFL_MAP["staffPosRaise1"],
    "B4": NOT_SMuFL_CODES["staffPosRaise0"],
    "A4": SMuFL_MAP["staffPosLower1"],
    "G4": SMuFL_MAP["staffPosLower2"],
    "F4": SMuFL_MAP["staffPosLower3"],
    "E4": SMuFL_MAP["staffPosLower4"],
    "D4": SMuFL_MAP["staffPosLower5"],
    "C4": SMuFL_MAP["staffPosLower6"],
    "B3": SMuFL_MAP["staffPosLower7"],
    "A3": SMuFL_MAP["staffPosLower8"],
    "G3": NOT_SMuFL_CODES["staffPosLower9"],
    "F3": NOT_SMuFL_CODES["staffPosLower10"],
    "E3": NOT_SMuFL_CODES["staffPosLower11"],
    "D3": NOT_SMuFL_CODES["staffPosLower12"],
    "C3": NOT_SMuFL_CODES["staffPosLower13"],
    "B2": NOT_SMuFL_CODES["staffPosLower14"],
    "A2": NOT_SMuFL_CODES["staffPosLower15"],
} as Record<Code & Word, Unicode & Word>

const BASS_CONDITIONAL_POSITION_ALIASES_MAP: Record<RecordKey<Code & Word>, Unicode & Word> = {
    "E5": NOT_SMuFL_CODES["staffPosRaise15"],
    "D5": NOT_SMuFL_CODES["staffPosRaise14"],
    "C5": NOT_SMuFL_CODES["staffPosRaise13"],
    "B4": NOT_SMuFL_CODES["staffPosRaise12"],
    "A4": NOT_SMuFL_CODES["staffPosRaise11"],
    "G4": NOT_SMuFL_CODES["staffPosRaise10"],
    "F4": NOT_SMuFL_CODES["staffPosRaise9"],
    "E4": SMuFL_MAP["staffPosRaise8"],
    "D4": SMuFL_MAP["staffPosRaise7"],
    "C4": SMuFL_MAP["staffPosRaise6"],
    "B3": SMuFL_MAP["staffPosRaise5"],
    "A3": SMuFL_MAP["staffPosRaise4"],
    "G3": SMuFL_MAP["staffPosRaise3"],
    "F3": SMuFL_MAP["staffPosRaise2"],
    "E3": SMuFL_MAP["staffPosRaise1"],
    "D3": NOT_SMuFL_CODES["staffPosRaise0"],
    "C3": SMuFL_MAP["staffPosLower1"],
    "B2": SMuFL_MAP["staffPosLower2"],
    "A2": SMuFL_MAP["staffPosLower3"],
    "G2": SMuFL_MAP["staffPosLower4"],
    "F2": SMuFL_MAP["staffPosLower5"],
    "E2": SMuFL_MAP["staffPosLower6"],
    "D2": SMuFL_MAP["staffPosLower7"],
    "C2": SMuFL_MAP["staffPosLower8"],
    "B1": NOT_SMuFL_CODES["staffPosLower9"],
    "A1": NOT_SMuFL_CODES["staffPosLower10"],
    "G1": NOT_SMuFL_CODES["staffPosLower11"],
    "F1": NOT_SMuFL_CODES["staffPosLower12"],
    "E1": NOT_SMuFL_CODES["staffPosLower13"],
    "D1": NOT_SMuFL_CODES["staffPosLower14"],
    "C1": NOT_SMuFL_CODES["staffPosLower15"],
} as Record<Code & Word, Unicode & Word>

export {
    TREBLE_CONDITIONAL_POSITION_ALIASES_MAP,
    BASS_CONDITIONAL_POSITION_ALIASES_MAP,
}
