import {RecordKey, Word} from "@sagittal/general"
import {NOT_SMuFL_CODES} from "../../notSmufl"
import {SMuFL_MAP} from "../../smufl"
import {Code, Unicode} from "../../types"

const TREBLE_CONDITIONAL_POSITION_ALIASES_MAP: Record<RecordKey<Code & Word>, Unicode & Word> = {
    "c7": NOT_SMuFL_CODES["staffPosRaise15"],
    "b6": NOT_SMuFL_CODES["staffPosRaise14"],
    "a6": NOT_SMuFL_CODES["staffPosRaise13"],
    "g6": NOT_SMuFL_CODES["staffPosRaise12"],
    "f6": NOT_SMuFL_CODES["staffPosRaise11"],
    "e6": NOT_SMuFL_CODES["staffPosRaise10"],
    "d6": NOT_SMuFL_CODES["staffPosRaise9"],
    "c6": SMuFL_MAP["staffPosRaise8"],
    "b5": SMuFL_MAP["staffPosRaise7"],
    "a5": SMuFL_MAP["staffPosRaise6"],
    "g5": SMuFL_MAP["staffPosRaise5"],
    "f5": SMuFL_MAP["staffPosRaise4"],
    "e5": SMuFL_MAP["staffPosRaise3"],
    "d5": SMuFL_MAP["staffPosRaise2"],
    "c5": SMuFL_MAP["staffPosRaise1"],
    "b4": NOT_SMuFL_CODES["staffPosRaise0"],
    "a4": SMuFL_MAP["staffPosLower1"],
    "g4": SMuFL_MAP["staffPosLower2"],
    "f4": SMuFL_MAP["staffPosLower3"],
    "e4": SMuFL_MAP["staffPosLower4"],
    "d4": SMuFL_MAP["staffPosLower5"],
    "c4": SMuFL_MAP["staffPosLower6"],
    "b3": SMuFL_MAP["staffPosLower7"],
    "a3": SMuFL_MAP["staffPosLower8"],
    "g3": NOT_SMuFL_CODES["staffPosLower9"],
    "f3": NOT_SMuFL_CODES["staffPosLower10"],
    "e3": NOT_SMuFL_CODES["staffPosLower11"],
    "d3": NOT_SMuFL_CODES["staffPosLower12"],
    "c3": NOT_SMuFL_CODES["staffPosLower13"],
    "b2": NOT_SMuFL_CODES["staffPosLower14"],
    "a2": NOT_SMuFL_CODES["staffPosLower15"],
} as Record<Code & Word, Unicode & Word>

const BASS_CONDITIONAL_POSITION_ALIASES_MAP: Record<RecordKey<Code & Word>, Unicode & Word> = {
    "e5": NOT_SMuFL_CODES["staffPosRaise15"],
    "d5": NOT_SMuFL_CODES["staffPosRaise14"],
    "c5": NOT_SMuFL_CODES["staffPosRaise13"],
    "b4": NOT_SMuFL_CODES["staffPosRaise12"],
    "a4": NOT_SMuFL_CODES["staffPosRaise11"],
    "g4": NOT_SMuFL_CODES["staffPosRaise10"],
    "f4": NOT_SMuFL_CODES["staffPosRaise9"],
    "e4": SMuFL_MAP["staffPosRaise8"],
    "d4": SMuFL_MAP["staffPosRaise7"],
    "c4": SMuFL_MAP["staffPosRaise6"],
    "b3": SMuFL_MAP["staffPosRaise5"],
    "a3": SMuFL_MAP["staffPosRaise4"],
    "g3": SMuFL_MAP["staffPosRaise3"],
    "f3": SMuFL_MAP["staffPosRaise2"],
    "e3": SMuFL_MAP["staffPosRaise1"],
    "d3": NOT_SMuFL_CODES["staffPosRaise0"],
    "c3": SMuFL_MAP["staffPosLower1"],
    "b2": SMuFL_MAP["staffPosLower2"],
    "a2": SMuFL_MAP["staffPosLower3"],
    "g2": SMuFL_MAP["staffPosLower4"],
    "f2": SMuFL_MAP["staffPosLower5"],
    "e2": SMuFL_MAP["staffPosLower6"],
    "d2": SMuFL_MAP["staffPosLower7"],
    "c2": SMuFL_MAP["staffPosLower8"],
    "b1": NOT_SMuFL_CODES["staffPosLower9"],
    "a1": NOT_SMuFL_CODES["staffPosLower10"],
    "g1": NOT_SMuFL_CODES["staffPosLower11"],
    "f1": NOT_SMuFL_CODES["staffPosLower12"],
    "e1": NOT_SMuFL_CODES["staffPosLower13"],
    "d1": NOT_SMuFL_CODES["staffPosLower14"],
    "c1": NOT_SMuFL_CODES["staffPosLower15"],
} as Record<Code & Word, Unicode & Word>

export {
    TREBLE_CONDITIONAL_POSITION_ALIASES_MAP,
    BASS_CONDITIONAL_POSITION_ALIASES_MAP,
}
